apiVersion: v1
kind: Service
metadata:
  #name: {{ template "spotTerminationexporter.fullname" . }}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
#    app: {{ template "spotTerminationexporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.spotTerminationexporter.service.type }}
  clusterIP: "None"
  ports:
  - name: http
    port: {{ default "9189" .Values.spotTerminationexporter.bindAddr }}
    targetPort: http
  selector:
    #app: "{{ template "spotTerminationexporter.fullname" . }}"
    app: "{{ .Chart.Name }}"
