kind: Service
apiVersion: v1
metadata:
  name: nginx-default-backend
  namespace: ingress-nginx
  labels:
    k8s-app: default-http-backend
    k8s-addon: ingress-nginx.addons.k8s.io
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    k8s-app: default-http-backend

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-default-backend
  namespace: ingress-nginx
  labels:
    k8s-app: default-http-backend
    k8s-addon: ingress-nginx.addons.k8s.io
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-default-backend
      k8s-addon: ingress-nginx.addons.k8s.io
      k8s-app: default-http-backend
  template:
    metadata:
      labels:
        app: nginx-default-backend
        k8s-addon: ingress-nginx.addons.k8s.io
        k8s-app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: k8s.gcr.io/defaultbackend:1.3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 1m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
